"""empty message

Revision ID: 5e9e2164402a
Revises: 9760062ab492
Create Date: 2019-12-28 22:51:40.036045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9e2164402a'
down_revision = '9760062ab492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('font_user',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('username', sa.String(length=11), nullable=False),
    sa.Column('_password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('realName', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.Column('signature', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Enum('UNKNOW', 'MALE', 'FEMALE', 'SECRET', name='gender'), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('font_user')
    # ### end Alembic commands ###
