"""empty message

Revision ID: f17a3b62d8be
Revises: 3b79b65c7989
Create Date: 2019-11-28 22:24:19.863485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f17a3b62d8be'
down_revision = '3b79b65c7989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', sa.String(length=50), nullable=False))
    op.drop_column('cms_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###
